import { useState } from "react";
import { HudBadge, HudButton, HudPanel } from "../../components/hud";
import { api } from "../../lib/api";
import type { CodexConnectionStatus, CodexPathCandidateDto } from "../../lib/types";

export function CodexSetupPanel({ allowDefer = false, onDeferred, onSaved }: { allowDefer?: boolean; onDeferred?: () => void; onSaved?: () => void }) {
  const [candidates, setCandidates] = useState<CodexPathCandidateDto[]>([]); const [path, setPath] = useState(""); const [manual, setManual] = useState(false); const [connection, setConnection] = useState<CodexConnectionStatus | null>(null); const [operation, setOperation] = useState<"detect" | "test" | "save" | null>(null); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
  const detect = async () => { setOperation("detect"); setError(""); setConnection(null); try { const found = await api.discoverCodexCandidates(); setCandidates(found); const recommended = found.find((item) => item.recommended) ?? found[0]; if (recommended) setPath(recommended.canonicalPath); } catch (reason) { setError(String(reason)); } finally { setOperation(null); } };
  const test = async () => { setOperation("test"); setError(""); setSaved(false); try { const status = await api.testCodexConnection(path.trim()); setConnection(status); if (status.available && status.authenticated) setPath(status.path); } catch (reason) { setConnection(null); setError(String(reason)); } finally { setOperation(null); } };
  const save = async () => { if (!connection?.available || !connection.authenticated || connection.path !== path.trim()) return; setOperation("save"); setError(""); try { await api.updateCodexPath(path.trim()); setSaved(true); onSaved?.(); } catch (reason) { setError(String(reason)); } finally { setOperation(null); } };
  const choose = (next: string) => { setPath(next); setConnection(null); setSaved(false); };
  return <HudPanel title="AI接続（Codex CLI）"><div className="settings-stack"><p className="empty-copy">端末内の候補だけを安全に検出します。候補を選んで接続テストに成功した後に保存します。</p><div className="form-actions"><HudButton type="button" onClick={() => void detect()} disabled={operation !== null}>{operation === "detect" ? "検出中…" : "Codexを自動検出"}</HudButton></div>{candidates.length > 0 && <fieldset className="codex-candidates"><legend>検出された候補</legend>{candidates.map((item) => <label key={item.canonicalPath}><input type="radio" name="codexCandidate" checked={!manual && path === item.canonicalPath} onChange={() => { setManual(false); choose(item.canonicalPath); }} /> <code>{item.canonicalPath}</code>{item.recommended ? "（推奨）" : ""}</label>)}</fieldset>}<label className="check-card"><input name="manualCodexPath" type="checkbox" checked={manual} onChange={(e) => { const nextManual = e.target.checked; setManual(nextManual); const recommended = candidates.find((item) => item.recommended) ?? candidates[0]; choose(nextManual ? path : recommended?.canonicalPath ?? ""); }} />別の場所を指定する</label>{manual && <label className="field">Codex CLIの絶対パス<input name="codexPath" autoComplete="off" value={path} onChange={(e) => choose(e.target.value)} placeholder="/opt/homebrew/bin/codex" aria-describedby="codex-path-help" /></label>}<p id="codex-path-help" className="form-help">見つからない場合は、ターミナルで <code>command -v codex</code> を実行して表示された絶対パスを入力してください。</p><div className="form-actions"><HudButton type="button" onClick={() => void test()} disabled={operation !== null || !path.trim()}>{operation === "test" ? "確認中…" : "選択した候補を接続テスト"}</HudButton><HudButton tone="green" type="button" onClick={() => void save()} disabled={operation !== null || !connection?.available || !connection.authenticated || connection.path !== path.trim()}>{operation === "save" ? "保存中…" : "READYの接続を保存"}</HudButton>{allowDefer && <HudButton type="button" onClick={onDeferred} disabled={operation !== null}>AI接続は後で</HudButton>}</div>{connection && <p role="status"><HudBadge tone={connection.available && connection.authenticated ? "green" : "gold"}>{connection.available && connection.authenticated ? "READY" : "要確認"}</HudBadge> {connection.message}{connection.version ? `（${connection.version}）` : ""} {connection.path ? <code>{connection.path}</code> : null}</p>}{saved && <p role="status">Codex CLIの接続先を保存しました。</p>}{error && <p role="alert">操作を完了できませんでした: {error}</p>}</div></HudPanel>;
}
