import { useState, type FormEvent } from "react";
import { HudBadge, HudButton, HudPanel } from "../../components/hud";
import type { FocusThemeDto, FocusThemeInput } from "../../lib/types";
import { SKILL_GROUPS, SKILL_NAMES } from "./skill-catalog";

const blankTheme = (sortOrder: number): FocusThemeInput => ({ id: null, title: "", desiredOutcome: "", whyNow: "", horizon: "quarter", status: "active", linkedSkillIds: [], sortOrder });
const toInput = (theme: FocusThemeDto): FocusThemeInput => ({ id: theme.id, title: theme.title, desiredOutcome: theme.desiredOutcome, whyNow: theme.whyNow, horizon: theme.horizon, status: theme.status, linkedSkillIds: theme.linkedSkillIds, sortOrder: theme.sortOrder });

export function FocusThemesEditor({ initialThemes, saving, error, onSave }: { initialThemes: FocusThemeDto[]; saving: boolean; error?: unknown; onSave: (themes: FocusThemeInput[]) => void }) {
  const [themes, setThemes] = useState<FocusThemeInput[]>(() => initialThemes.map(toInput));
  const update = (index: number, patch: Partial<FocusThemeInput>) => setThemes((current) => current.map((theme, i) => i === index ? { ...theme, ...patch } : theme));
  const submit = (event: FormEvent) => { event.preventDefault(); onSave(themes.filter((theme) => theme.title.trim()).map((theme, index) => ({ ...theme, sortOrder: index }))); };
  return <HudPanel title="個人テーマ"><form className="feature-form" onSubmit={submit}><p className="form-help">固定スキルを組み合わせ、今の仕事や暮らしに沿ったテーマを複数作れます。過去の文脈を残すため、既存テーマは削除せず「完了」にします。</p>{themes.length === 0 && <p className="empty-copy">個人テーマはまだありません。必要なときに追加できます。</p>}{themes.map((theme, index) => <fieldset className="theme-editor" key={theme.id ?? `new-${index}`}><legend>テーマ {index + 1}</legend><label className="field">テーマ名<input name={`theme-${index}-title`} autoComplete="off" required value={theme.title} onChange={(e) => update(index, { title: e.target.value })} /></label><label className="field">実現したい変化<textarea name={`theme-${index}-outcome`} autoComplete="off" value={theme.desiredOutcome} onChange={(e) => update(index, { desiredOutcome: e.target.value })} /></label><label className="field">今取り組む理由<textarea name={`theme-${index}-why`} autoComplete="off" value={theme.whyNow} onChange={(e) => update(index, { whyNow: e.target.value })} /></label><div className="theme-options"><label className="field">期間<select name={`theme-${index}-horizon`} autoComplete="off" value={theme.horizon} onChange={(e) => update(index, { horizon: e.target.value as FocusThemeInput["horizon"] })}><option value="now">今</option><option value="quarter">今四半期</option><option value="year">今年</option><option value="ongoing">継続</option></select></label><label className="field">状態<select name={`theme-${index}-status`} autoComplete="off" value={theme.status} onChange={(e) => update(index, { status: e.target.value as FocusThemeInput["status"] })}><option value="active">進行中</option><option value="paused">一時停止</option><option value="completed">完了</option></select></label></div><fieldset className="theme-skills"><legend>関連する固定スキル</legend>{SKILL_GROUPS.flatMap(([, , items]) => items).map(([id]) => <label className="check-card" key={id}><input name={`theme-${index}-skills`} type="checkbox" checked={theme.linkedSkillIds.includes(id)} onChange={() => update(index, { linkedSkillIds: theme.linkedSkillIds.includes(id) ? theme.linkedSkillIds.filter((skill) => skill !== id) : [...theme.linkedSkillIds, id] })} />{SKILL_NAMES.get(id)}</label>)}</fieldset>{theme.id ? <HudButton type="button" onClick={() => update(index, { status: "completed" })} disabled={theme.status === "completed"}>このテーマを完了にする</HudButton> : <HudButton className="button-danger" type="button" onClick={() => setThemes((current) => current.filter((_, i) => i !== index))}>追加を取り消す</HudButton>}</fieldset>)}<div className="form-actions"><HudButton type="button" onClick={() => setThemes((current) => [...current, blankTheme(current.length)])} disabled={themes.length >= 10}>テーマを追加</HudButton><HudButton tone="gold" type="submit" disabled={saving}>{saving ? "保存中…" : "個人テーマを保存"}</HudButton></div>{error ? <p role="alert">個人テーマを保存できませんでした: {String(error)}</p> : null}</form></HudPanel>;
}

export function FocusThemesSummary({ themes }: { themes: FocusThemeDto[] }) { return themes.length ? <ul className="focus-theme-list">{themes.map((theme) => <li key={theme.id}><strong>{theme.title}</strong> <HudBadge tone={theme.status === "active" ? "green" : "purple"}>{theme.status === "active" ? "進行中" : theme.status === "paused" ? "一時停止" : "完了"}</HudBadge><p>{theme.desiredOutcome}</p><p className="empty-copy">関連: {theme.linkedSkillIds.map((id) => SKILL_NAMES.get(id) ?? id).join("・") || "未設定"}</p></li>)}</ul> : <p className="empty-copy">個人テーマはまだありません。</p>; }
