import { useState, type FormEvent, type ReactNode } from "react";
import { HudButton, HudPanel } from "../../components/hud";
import type { QuestStyle } from "../../lib/types";
import { emptyProfile, type ProfileFormValue } from "./profile-model";
import { SKILL_GROUPS } from "./skill-catalog";

export function ProfileForm({ initialValue = emptyProfile, mode, submitting, error, footer, onReload, onSubmit }: { initialValue?: ProfileFormValue; mode: "create" | "edit"; submitting: boolean; error?: unknown; footer?: ReactNode; onReload?: () => void; onSubmit: (value: ProfileFormValue) => void }) {
  const [value, setValue] = useState(initialValue); const [domains, setDomains] = useState(initialValue.domainsAndTechnologies.join(", "));
  const set = <K extends keyof ProfileFormValue>(key: K, next: ProfileFormValue[K]) => setValue((current) => ({ ...current, [key]: next }));
  const toggleSkill = (id: string) => set("focusSkillIds", value.focusSkillIds.includes(id) ? value.focusSkillIds.filter((skill) => skill !== id) : value.focusSkillIds.length < 3 ? [...value.focusSkillIds, id] : value.focusSkillIds);
  const submit = (event: FormEvent) => { event.preventDefault(); onSubmit({ ...value, domainsAndTechnologies: domains.split(/[,、\n]/).map((item) => item.trim()).filter(Boolean) }); };
  return <form className="feature-form" onSubmit={submit} aria-label={mode === "create" ? "成長プロフィールを作成" : "成長プロフィールを編集"}>
    <HudPanel title="現在地と経験"><label className="field">現在の役割<input name="role" autoComplete="organization-title" required value={value.role} onChange={(e) => set("role", e.target.value)} /></label><label className="field">これまでの経験・背景<textarea name="background" autoComplete="off" value={value.background} onChange={(e) => set("background", e.target.value)} /></label><label className="field">現在の責任・担当<textarea name="currentResponsibilities" autoComplete="off" value={value.currentResponsibilities} onChange={(e) => set("currentResponsibilities", e.target.value)} /></label><label className="field">領域・技術（カンマ区切り）<input name="domainsAndTechnologies" autoComplete="off" value={domains} onChange={(e) => setDomains(e.target.value)} aria-describedby="domains-help" /></label><p id="domains-help" className="form-help">例：プロダクト設計, TypeScript, 顧客折衝</p></HudPanel>
    <HudPanel title="成長の方向"><label className="field">成長目標<textarea name="growthGoal" autoComplete="off" required value={value.growthGoal} onChange={(e) => set("growthGoal", e.target.value)} /></label><label className="field">その目標を大切にする理由<textarea name="motivation" autoComplete="off" value={value.motivation} onChange={(e) => set("motivation", e.target.value)} /></label><label className="field">現在の課題<textarea name="currentChallenges" autoComplete="off" value={value.currentChallenges} onChange={(e) => set("currentChallenges", e.target.value)} /></label><label className="field">最近うまくいったこと<textarea name="recentSuccess" autoComplete="off" value={value.recentSuccess} onChange={(e) => set("recentSuccess", e.target.value)} /></label></HudPanel>
    <HudPanel title="重点スキル（1〜3個）"><p id="focus-skill-help" className="form-help">今とくに意識したいものを選びます。3個選択中は、別の項目を外すと変更できます。</p><div className="skill-picker" aria-describedby="focus-skill-help">{SKILL_GROUPS.map(([, category, items]) => <fieldset key={category}><legend>{category}</legend>{items.map(([id, label]) => <label className="check-card" key={id}><input name="focusSkillIds" type="checkbox" checked={value.focusSkillIds.includes(id)} onChange={() => toggleSkill(id)} /><span>{label}</span></label>)}</fieldset>)}</div><p className="selection-count" role="status" aria-live="polite">{value.focusSkillIds.length} / 3 選択中</p></HudPanel>
    <HudPanel title="クエストの好み"><label className="field">週に使える時間（分）<input name="weeklyMinutes" autoComplete="off" required min="1" max="10080" type="number" value={value.weeklyMinutes} onChange={(e) => set("weeklyMinutes", Number(e.target.value))} /></label><label className="field">1クエストの目安（分）<input name="preferredQuestMinutes" autoComplete="off" required min="5" max="120" type="number" value={value.preferredQuestMinutes} onChange={(e) => set("preferredQuestMinutes", Number(e.target.value))} /></label><label className="field">クエストスタイル<select name="preferredQuestStyle" autoComplete="off" value={value.preferredQuestStyle} onChange={(e) => set("preferredQuestStyle", e.target.value as QuestStyle)}><option value="balanced">バランス</option><option value="work_integrated">日々の仕事に組み込む</option><option value="practice">練習する</option><option value="reflection">振り返る</option></select></label><label className="field">守りたい制約<textarea name="constraints" autoComplete="off" value={value.constraints} onChange={(e) => set("constraints", e.target.value)} /></label><label className="field">避けたいクエスト<textarea name="excludedQuestPatterns" autoComplete="off" value={value.excludedQuestPatterns} onChange={(e) => set("excludedQuestPatterns", e.target.value)} /></label></HudPanel>
    {footer}{error ? <div role="alert"><p>プロフィールを保存できませんでした: {String(error)}</p>{onReload ? <HudButton type="button" onClick={onReload}>最新プロフィールを再読み込み</HudButton> : null}</div> : null}<div className="onboarding-submit"><HudButton tone="gold" type="submit" disabled={submitting || value.focusSkillIds.length < 1 || value.focusSkillIds.length > 3}>{submitting ? "保存中…" : mode === "create" ? "プロフィールを保存してAI設定へ" : "プロフィールを保存"}</HudButton></div>
  </form>;
}
