import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useRef, useState, type Dispatch, type SetStateAction } from "react";
import { Link, useParams } from "react-router-dom";
import { HudBadge, HudButton, HudPanel } from "../../components/hud";
import { api } from "../../lib/api";
import type { CandidateDecision, CandidateDecisionInput, InterviewQuestionDto, SkillCandidateDto } from "../../lib/types";
import { SKILL_GROUPS, SKILL_NAMES } from "../profile";

type Draft = { decision: CandidateDecision; reason: string; evidence: string; skillId: string; specializedSkillName: string };
const toDraft = (candidate: SkillCandidateDto): Draft => ({ decision: candidate.decision, reason: candidate.reason, evidence: candidate.evidence, skillId: candidate.skillId, specializedSkillName: candidate.specializedSkillName ?? "" });

export function AnalysisPage() {
  const { activityId = "" } = useParams();
  const client = useQueryClient();
  const [payload, setPayload] = useState("");
  const [questPayload, setQuestPayload] = useState<string | null>(null);
  const [startedAnalysisId, setStartedAnalysisId] = useState<string | null>(null);
  const [ignorePrevious, setIgnorePrevious] = useState(false);
  const [drafts, setDrafts] = useState<Record<string, Draft>>({});
  const answerStatusRef = useRef<HTMLDivElement>(null);
  const activity = useQuery({ queryKey: ["activity", activityId], queryFn: () => api.getActivity(activityId), enabled: Boolean(activityId) });
  const workflow = useQuery({ queryKey: ["activity-workflow", activityId], queryFn: () => api.getActivityWorkflow(activityId), enabled: Boolean(activityId) });
  const preview = useQuery({ queryKey: ["analysis-preview", activityId], queryFn: () => api.getAnalysisPreview(activityId), enabled: Boolean(activityId) });
  const existingAnalysisId = ignorePrevious ? null : activity.data?.analyses[0]?.id ?? null;
  const analysisId = startedAnalysisId ?? existingAnalysisId;
  const analysis = useQuery({ queryKey: ["analysis", analysisId], queryFn: () => api.getActivityAnalysis(analysisId!), enabled: Boolean(analysisId), refetchInterval: (query) => ["pending", "running"].includes(query.state.data?.status ?? "") ? 1500 : false });
  const submittedPayload = payload || preview.data?.submittedPayload || "";
  const start = useMutation({ mutationFn: () => api.startActivityAnalysis({ activityId, submittedPayload }), onSuccess: (job) => { setStartedAnalysisId(job.id); setIgnorePrevious(false); void client.invalidateQueries({ queryKey: ["activity-workflow", activityId] }); void client.invalidateQueries({ queryKey: ["activity-inbox"] }); } });
  const cancel = useMutation({ mutationFn: () => api.cancelActivityAnalysis(analysisId!), onSuccess: () => { void client.invalidateQueries({ queryKey: ["analysis", analysisId] }); void client.invalidateQueries({ queryKey: ["activity-workflow", activityId] }); } });
  const answer = useMutation({ mutationFn: (input: { question: InterviewQuestionDto; answerState: "answered" | "unknown" | "skipped" | "deferred"; answer: string | null }) => api.answerActivityQuestion({ sessionId: input.question.sessionId, questionId: input.question.questionId, answerState: input.answerState, answer: input.answer }), onSuccess: async (nextWorkflow) => { client.setQueryData(["activity-workflow", activityId], nextWorkflow); await Promise.all([client.invalidateQueries({ queryKey: ["analysis-preview", activityId], exact: true }), client.invalidateQueries({ queryKey: ["activity-inbox"] })]); } });
  const decisions = (analysis.data?.skillCandidates ?? []).map((candidate): CandidateDecisionInput => { const draft = drafts[candidate.id] ?? toDraft(candidate); return { candidateId: candidate.id, decision: draft.decision === "pending" ? "rejected" : draft.decision, editedReason: draft.decision === "edited" ? draft.reason : null, editedEvidence: draft.decision === "edited" ? draft.evidence : null, editedSkillId: draft.decision === "edited" ? draft.skillId : null, editedSpecializedSkillName: draft.decision === "edited" ? draft.specializedSkillName.trim() || null : null }; });
  const allDecided = (analysis.data?.skillCandidates ?? []).every((candidate) => { const draft = drafts[candidate.id] ?? toDraft(candidate); return draft.decision !== "pending" && (draft.decision !== "edited" || (Boolean(draft.reason.trim()) && draft.reason.length <= 1_000 && Boolean(draft.evidence.trim()) && draft.evidence.length <= 1_000 && draft.specializedSkillName.length <= 80)); });
  const confirm = useMutation({ mutationFn: () => api.confirmActivityAnalysis({ analysisId: analysisId!, candidateDecisions: decisions }), onSuccess: () => { void client.invalidateQueries({ queryKey: ["analysis", analysisId] }); void client.invalidateQueries({ queryKey: ["activity-workflow", activityId] }); void client.invalidateQueries({ queryKey: ["activity-inbox"] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); void client.invalidateQueries({ queryKey: ["skills"] }); } });
  const questPreview = useQuery({ queryKey: ["quest-preview", activityId, analysisId], queryFn: () => api.getQuestPreview({ activityId, analysisId: analysisId! }), enabled: Boolean(analysisId && analysis.data?.status === "confirmed"), retry: false });
  const quest = useMutation({ mutationFn: () => api.generateQuest({ activityId, analysisId: analysisId!, submittedPayload: questPayload ?? questPreview.data?.submittedPayload ?? null }), onSuccess: () => { void client.invalidateQueries({ queryKey: ["quests"] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); } });
  const retry = () => { setStartedAnalysisId(null); setIgnorePrevious(true); setDrafts({}); setPayload(""); setQuestPayload(null); };
  const analysisStatus = analysis.data?.status;
  useEffect(() => {
    if (!analysisId || !analysisStatus || !["succeeded", "failed", "cancelled", "confirmed"].includes(analysisStatus)) return;
    void Promise.all([
      client.invalidateQueries({ queryKey: ["activity-workflow", activityId] }),
      client.invalidateQueries({ queryKey: ["activity", activityId] }),
      client.invalidateQueries({ queryKey: ["activity-inbox"] }),
      client.invalidateQueries({ queryKey: ["activities"] }),
    ]);
  }, [activityId, analysisId, analysisStatus, client]);
  useEffect(() => {
    if (answer.isSuccess) answerStatusRef.current?.focus();
  }, [answer.isSuccess, workflow.data?.state]);

  if (activity.isPending || preview.isPending || workflow.isPending) return <HudPanel title="AI分析"><p className="empty-copy" role="status">送信内容を準備しています…</p></HudPanel>;
  if (activity.isError || preview.isError || workflow.isError) return <HudPanel title="AI分析"><p role="alert">{String(activity.error ?? preview.error ?? workflow.error)}</p></HudPanel>;
  const result = analysis.data;
  return <section className="feature-page feature-page--narrow" aria-labelledby="analysis-title"><header className="page-heading"><div><p className="hud-kicker">HUMAN CONFIRMATION REQUIRED</p><h1 id="analysis-title">経験を整理する</h1><p>AIは提案者です。事実・推測・スキル候補を分け、あなたが確認したものだけを証拠にします。</p></div><Link to="/activities/inbox">インボックスへ</Link></header>
    {!analysisId && <HudPanel title="Codexへ送信する内容"><p className="cloud-notice"><HudBadge tone="gold">CLOUD</HudBadge> {preview.data.cloudInferenceNotice}</p><label className="field">送信するJSON<textarea name="analysisPayload" autoComplete="off" className="json-editor" aria-label="送信するJSON" value={submittedPayload} onChange={(event) => setPayload(event.target.value)} rows={14} spellCheck={false} /></label><div className="form-actions"><HudButton tone="gold" onClick={() => start.mutate()} disabled={start.isPending}>{start.isPending ? "送信中…" : "内容を確認して送信"}</HudButton></div>{start.error && <p role="alert">{String(start.error)}</p>}</HudPanel>}
    {analysisId && analysis.isPending && <HudPanel title="AI分析"><p role="status">分析状態を読み込んでいます…</p></HudPanel>}
    {analysis.isError && <HudPanel title="AI分析"><p role="alert">{String(analysis.error)}</p><HudButton onClick={() => void analysis.refetch()}>再読込</HudButton></HudPanel>}
    {result && <AnalysisResult result={result} workflowState={workflow.data.state} drafts={drafts} setDrafts={setDrafts} onConfirm={() => confirm.mutate()} allDecided={allDecided} confirming={confirm.isPending} onCancel={() => cancel.mutate()} cancelling={cancel.isPending} onRetry={retry} />}
    {result?.status === "confirmed" && <QuestPreview preview={questPreview.data} loading={questPreview.isPending} error={questPreview.error} payload={questPayload ?? questPreview.data?.submittedPayload ?? ""} onPayload={setQuestPayload} onGenerate={() => quest.mutate()} generating={quest.isPending} />}
    {result?.nextQuestion && workflow.data.state === "needs_input" && <QuestionCard question={result.nextQuestion} pending={answer.isPending} error={answer.error} onAnswer={(answerState, value) => answer.mutate({ question: result.nextQuestion!, answerState, answer: value })} />}
    {workflow.data.currentQuestion && workflow.data.state === "needs_input" && !result?.nextQuestion && <QuestionCard question={workflow.data.currentQuestion} pending={answer.isPending} error={answer.error} onAnswer={(answerState, value) => answer.mutate({ question: workflow.data.currentQuestion!, answerState, answer: value })} />}
    {answer.isSuccess && workflow.data.state === "assessable" && <div ref={answerStatusRef} tabIndex={-1} className="result-message" role="status"><p>回答を保存しました。内容を反映した新しい整理案を作れます。</p><HudButton onClick={retry}>回答を反映して再解析</HudButton></div>}
    {answer.isSuccess && workflow.data.state === "needs_input" && <div ref={answerStatusRef} tabIndex={-1} className="result-message" role="status">質問を後で答える項目として保存しました。整理インボックスから再開できます。</div>}
    {confirm.data && <p className="result-message" role="status">{confirm.data.confirmedObservationCount}件の証拠を確定し、{confirm.data.xpAwarded} XPを追加しました。</p>}
    {quest.data && <p className="result-message" role="status">クエスト「{quest.data.title}」を作成しました。</p>}
    {confirm.error && <p role="alert">{String(confirm.error)}</p>}{quest.error && <p role="alert">{String(quest.error)}</p>}
  </section>;
}

function QuestionCard({ question, onAnswer, pending, error }: { question: InterviewQuestionDto; onAnswer: (state: "answered" | "unknown" | "skipped" | "deferred", answer: string | null) => void; pending: boolean; error: unknown }) {
  const [value, setValue] = useState("");
  const needsValue = Boolean(value.trim());
  return <HudPanel title="AIからの確認"><div className="interview-card"><HudBadge tone="purple">ONE QUESTION</HudBadge><h2>{question.text}</h2><p className="form-help">なぜ聞くの？ {question.whyItMatters}</p>{question.answerType === "single_choice" ? <div className="interview-choices" role="radiogroup" aria-label={question.text}>{question.choices.map((choice) => <label key={choice.value}><input type="radio" name={`question-${question.questionId}`} value={choice.value} checked={value === choice.value} onChange={() => setValue(choice.value)} />{choice.label}</label>)}</div> : <label className="field">{question.answerType === "number" ? "数値" : "回答"}<input name={`answer-${question.questionId}`} autoComplete="off" type={question.answerType === "number" ? "number" : "text"} value={value} onChange={(event) => setValue(event.target.value)} /></label>}<div className="form-actions"><HudButton tone="gold" onClick={() => onAnswer("answered", value)} disabled={pending || !needsValue}>{pending ? "保存中…" : "回答を保存"}</HudButton><HudButton onClick={() => onAnswer("unknown", null)} disabled={pending}>わからない</HudButton><HudButton onClick={() => onAnswer("skipped", null)} disabled={pending}>スキップ</HudButton><HudButton tone="purple" onClick={() => onAnswer("deferred", null)} disabled={pending}>後で答える</HudButton></div>{error ? <p role="alert">回答を保存できませんでした: {String(error)}</p> : null}</div></HudPanel>;
}

function QuestPreview({ preview, loading, error, payload, onPayload, onGenerate, generating }: { preview: Awaited<ReturnType<typeof api.getQuestPreview>> | undefined; loading: boolean; error: unknown; payload: string; onPayload: (value: string) => void; onGenerate: () => void; generating: boolean }) {
  return <HudPanel title="次のクエストを提案"><p className="form-help">クエストも、送信する内容を確認・編集してから生成します。直接生成はしません。</p>{loading && <p role="status">クエストの送信内容を準備しています…</p>}{error ? <p role="alert">送信内容を準備できませんでした: {String(error)}</p> : null}{preview && <><p className="cloud-notice"><HudBadge tone="gold">CLOUD</HudBadge> {preview.cloudInferenceNotice}</p><label className="field">送信するJSON<textarea name="questPayload" autoComplete="off" className="json-editor" aria-label="クエストに送信するJSON" value={payload} onChange={(event) => onPayload(event.target.value)} rows={12} spellCheck={false} /></label><div className="form-actions"><HudButton tone="purple" onClick={onGenerate} disabled={generating}>{generating ? "生成中…" : "内容を確認して提案を生成"}</HudButton></div></>}</HudPanel>;
}

function AnalysisResult({ result, workflowState, drafts, setDrafts, onConfirm, allDecided, confirming, onCancel, cancelling, onRetry }: { result: Awaited<ReturnType<typeof api.getActivityAnalysis>>; workflowState: string; drafts: Record<string, Draft>; setDrafts: Dispatch<SetStateAction<Record<string, Draft>>>; onConfirm: () => void; allDecided: boolean; confirming: boolean; onCancel: () => void; cancelling: boolean; onRetry: () => void }) {
  if (["pending", "running"].includes(result.status)) return <HudPanel title="Codexで分析中"><div className="analysis-running"><span className="scan-indicator" aria-hidden="true" /><p role="status">分析中です。画面を閉じても活動の原文は保存されています。</p><HudButton tone="purple" onClick={onCancel} disabled={cancelling}>{cancelling ? "取消中…" : "分析をキャンセル"}</HudButton></div></HudPanel>;
  if (result.status === "failed" || result.status === "cancelled") return <HudPanel title="分析を完了できませんでした"><p role="alert">{result.errorMessage ?? "分析を完了できませんでした。"}</p><p className="empty-copy">活動は保持されています。送信内容を確認して、新しい分析として再試行できます。</p><HudButton tone="gold" onClick={onRetry}>送信内容に戻って再試行</HudButton></HudPanel>;
  if (result.status === "confirmed") return <HudPanel title="分析を確定しました"><HudBadge tone="green">CONFIRMED</HudBadge><p>確認済みの証拠だけがスキル観測へ反映されています。</p></HudPanel>;
  const needsInput = workflowState === "needs_input";
  const reviewReady = workflowState === "review_pending";
  return <HudPanel title="分析候補"><div className="analysis-summary"><HudBadge tone="purple">AI SUGGESTION</HudBadge>{result.summary && <p>{result.summary}</p>}<FactList title="今回確認できたこと" facts={result.confirmedFacts} empty="まだ確定できる事実はありません。" tone="green" /> <FactList title="まだ確認できていないこと" facts={result.unconfirmedFacts} empty="不足情報はありません。" tone="gold" />{result.outcomes.length > 0 && <><h3>観測された成果</h3><ul>{result.outcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul></>}{result.missingInformationQuestion && <p className="missing-question"><strong>不足情報：</strong>{result.missingInformationQuestion}</p>}</div>{needsInput && <p className="confirmation-block" role="status">AIの質問に回答・スキップ・後回しを選ぶまで、分析は確定できません。</p>}{!needsInput && !reviewReady && <p className="confirmation-block" role="status">確認状態を同期しています。完了すると判断を確定できます。</p>}<div className="candidate-list">{result.skillCandidates.length === 0 ? <p className="empty-copy">スキル候補はありません。確認できた事実だけを残し、必要なら再解析できます。</p> : result.skillCandidates.map((candidate) => <CandidateCard key={candidate.id} candidate={candidate} draft={drafts[candidate.id] ?? toDraft(candidate)} update={(patch) => setDrafts((current) => ({ ...current, [candidate.id]: { ...(current[candidate.id] ?? toDraft(candidate)), ...patch } }))} />)}</div><p className="form-help">候補ごとに採用・編集・却下を選んでください。未判断の候補がある間は確定できません。</p><div className="form-actions"><HudButton tone="green" onClick={onConfirm} disabled={confirming || !reviewReady || !allDecided}>{confirming ? "確定中…" : "判断を確定する（+20 XP）"}</HudButton><HudButton onClick={onRetry}>AIに再解析を依頼</HudButton></div></HudPanel>;
}

function FactList({ title, facts, empty, tone }: { title: string; facts: string[]; empty: string; tone: "green" | "gold" }) { return <div className={`fact-list fact-list--${tone}`}><h3>{title}</h3>{facts.length ? <ul>{facts.map((fact) => <li key={fact}>{fact}</li>)}</ul> : <p>{empty}</p>}</div>; }

function CandidateCard({ candidate, draft, update }: { candidate: SkillCandidateDto; draft: Draft; update: (patch: Partial<Draft>) => void }) { const invalidEdit = draft.decision === "edited" && (!draft.reason.trim() || draft.reason.length > 1_000 || !draft.evidence.trim() || draft.evidence.length > 1_000 || draft.specializedSkillName.length > 80); return <fieldset className="candidate-card"><legend>{SKILL_NAMES.get(draft.skillId) ?? draft.skillId} <span>確度 {Math.round(candidate.confidence * 100)}%</span></legend><div className="candidate-decisions"><label><input name={`decision-${candidate.id}`} type="radio" checked={draft.decision === "accepted"} onChange={() => update({ decision: "accepted" })} />採用</label><label><input name={`decision-${candidate.id}`} type="radio" checked={draft.decision === "edited"} onChange={() => update({ decision: "edited" })} />編集して採用</label><label><input name={`decision-${candidate.id}`} type="radio" checked={draft.decision === "rejected"} onChange={() => update({ decision: "rejected" })} />却下</label></div><p className="form-help">{draft.decision === "pending" ? "まだ判断されていません。" : invalidEdit ? "編集して採用する場合、理由と証拠は必須です（各1000文字以内、専門名は80文字以内）。" : ""}</p><label className="field">固定スキル<select name={`skill-${candidate.id}`} autoComplete="off" disabled={draft.decision !== "edited"} value={draft.skillId} onChange={(event) => update({ skillId: event.target.value })}>{SKILL_GROUPS.map(([, category, skills]) => <optgroup key={category} label={category}>{skills.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</optgroup>)}</select></label><label className="field">専門スキル名（任意）<input name={`specialized-${candidate.id}`} autoComplete="off" disabled={draft.decision !== "edited"} maxLength={80} value={draft.specializedSkillName} placeholder="例：SQL最適化…" onChange={(event) => update({ specializedSkillName: event.target.value })} /></label><label className="field">候補の理由<textarea name={`reason-${candidate.id}`} autoComplete="off" disabled={draft.decision !== "edited"} required={draft.decision === "edited"} maxLength={1_000} value={draft.reason} onChange={(event) => update({ reason: event.target.value })} /></label><label className="field">証拠<textarea name={`evidence-${candidate.id}`} autoComplete="off" disabled={draft.decision !== "edited"} required={draft.decision === "edited"} maxLength={1_000} value={draft.evidence} onChange={(event) => update({ evidence: event.target.value })} /></label></fieldset>; }
